//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocionicProjectWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerTable
    {
        public bool Answer1 { get; set; }
        public bool Answer2 { get; set; }
        public bool Answer3 { get; set; }
        public bool Answer4 { get; set; }
        public bool Answer5 { get; set; }
        public bool Answer6 { get; set; }
        public bool Answer7 { get; set; }
        public bool Answer8 { get; set; }
        public bool Answer9 { get; set; }
        public bool Answer10 { get; set; }
        public bool Answer11 { get; set; }
        public bool Answer12 { get; set; }
        public bool Answer13 { get; set; }
        public bool Answer14 { get; set; }
        public bool Answer15 { get; set; }
        public bool Answer16 { get; set; }
        public bool Answer17 { get; set; }
        public bool Answer18 { get; set; }
        public bool Answer19 { get; set; }
        public bool Answer20 { get; set; }
        public bool Answer21 { get; set; }
        public bool Answer22 { get; set; }
        public bool Answer23 { get; set; }
        public bool Answer24 { get; set; }
        public bool Answer25 { get; set; }
        public bool Answer26 { get; set; }
        public bool Answer27 { get; set; }
        public bool Answer28 { get; set; }
        public int id { get; set; }
    
        public virtual Results Results { get; set; }
    }
}
