//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocionicProjectWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SocionicEntities : DbContext
    {
        public SocionicEntities()
            : base("name=SocionicEntities")
        {
          //  this.Database.Connection.ConnectionString = "User ID=RuSh48;Password=RuSh25121989";
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnswerTable> AnswerTable { get; set; }
        public virtual DbSet<Results> Results { get; set; }
    }
}
